### ISSUE TITLE
Hyperlinks on Hackage not present

### ISSUE THREAD

**Issue by mhwombat** [qnikst/imagemagick#29]
Currently there are no hyperlinks to package documentation on http://hackage.haskell.org/package/imagemagick

Issue #2 calls for the addition of some haddock comments, but this is different. Even without comments, the hackage site should be able to show all the definitions exported by each module. Armed with that and the information at http://www.imagemagick.org/Usage/, the average user could probably figure out how to use the package.

imagemagick-0.0.3 was the last version to include any hyperlinks to documentation. I briefly examined the build logs at http://hackage.haskell.org/package/imagemagick-0.0.3.5/reports/1/log, and there is a failure at the end but I can't tell what the problem is. 

In the meantime, we can examine the source code on github to find the names of functions to call.

**Comment by jonkri** [comment]
+1

**Comment by qnikst** [comment]
Fixed for the latest uploaded version. Sorry for delay.

**Comment by qnikst** [comment]
Reopen, as some links still missing, will try to understand why and fix.

**Comment by jonkri** [comment]
Thanks!

**Comment by qnikst** [comment]
Fixed finally.
