### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by davidsiefert** [qnikst/imagemagick#32]
Had to install libmagickwand-dev >= 6.8 to get this building....

**Comment by davidsiefert** [comment]
on ubuntu...

**Comment by davidsiefert** [comment]
Update: I can build this project once I have ImageMagick sources built and installed, however I am still having considerable difficulty getting the JPEG delegate working...  Pull request is currently failing the build due to other issues that are unrelated.

**Comment by qnikst** [comment]
Yeah, thanks for PR and sorry for slacking, I'll fix those errors and merge it soon.

**Comment by davidsiefert** [comment]
No worries!  I'm planning on trying to fix these things as well so we can get a passing build.  Just wanted to update the ticket so other people knew there was something being worked on.  Thanks! :smile:

**Comment by qnikst** [comment]
Hi, I've merged your PR, can we consider this task as solved?
