### ISSUE TITLE
`readImage wand "xc:white"` throws an exception on windows

### ISSUE THREAD

**Issue by mwu-tow** [qnikst/imagemagick#35]
It is currently impossible to properly call MagickWand `readImage` function with "special" filename expression like `"xc:white"` on Windows. 

Consider the `readImage` function as defined here:
https://github.com/qnikst/imagemagick/blob/master/Graphics/ImageMagick/MagickWand/WandImage.hs#L914
`readImage :: (MonadResource m) => Ptr MagickWand -> FilePath -> m ()`

The function takes the `Filesystem.Path.CurrentOS`'s `FilePath` forcing the caller to build value of such type from `"xc:white"`. However, the colon character on Windows has special meaning in path — it separates disk letter from the rest of path. Therefore when constructing `FilePath` from `"xc:white"` it gets converted into `"X:\\"`. Then readImage throws exception about being `unable to open image \` — that makes some sense, given what's happening.

I think that `readImage` should not take the strongly typed `FilePath` because the argument is not necessarily a filesystem path — it can be also a special expression like `"xc:white"` that is not representable as `FilePath` on some operating systems.

**Comment by qnikst** [comment]
Fixed by https://github.com/qnikst/imagemagick/pull/40. Will it work for you?
