### ISSUE TITLE
Support the latest resourcet

### ISSUE THREAD

**Issue by Yuras** [qnikst/imagemagick#47]
Is it possible to support `resourcet-1.2.*`?

It's a bit more complicated then just updating the upper bound since `resourcet` depends on `exceptions` instead of `monad-control`, and incompatible changes are necessary. It could be easier just to drop older `resourcet` support. What do you think?

**Comment by Yuras** [comment]
Here is a possible change: https://github.com/Yuras/imagemagick/commit/a683fcefdb12badc5462e5dca836577089a4da3d

**Comment by qnikst** [comment]
For some reason, I've missed the notification. Thanks! I'll apply your patch tonight!

**Comment by Yuras** [comment]
I see you already merged it, thanks!
